spring:
  kafka:
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      bootstrap-servers: localhost:9101
    consumer:
      bootstrap-servers: localhost:9101
    bootstrap-servers: localhost:9101